language: rust
os: linux
rust:
- stable
- nightly
env: RUST_BACKTRACE=full
script: cargo test

matrix:
  include:
  - name: no-std
    os: linux
    rust: stable
    script:
    - rustup target add thumbv6m-none-eabi
    - cargo check --target thumbv6m-none-eabi --no-default-features
